name: Check C reference implementation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: C ref - make RUN_ALL
      run: make -C ref RUN_ALL
